#!/bin/sh 
# Copyright (c) 2004-2015 NVIDIA CORPORATION. All rights reserved.
# Unmount / Eject script 
# Version 1.0 Jun 17, 2004
#
# NVIDIA CORPORATION and its licensors retain all intellectual property
# and proprietary rights in and to this software, related documentation
# and any modifications thereto.  Any use, reproduction, disclosure or
# distribution of this software and related documentation without an express
# license agreement from NVIDIA CORPORATION is strictly prohibited.

# Note: This should be replaced by a binary that runs setuid root
# that can always eject the disk

if [ -z "$1" ]; then
    echo usage: $0 /dev/your_cdrom_device
    echo you did: $0 $1
    exit
fi

umount $1
eject $1

