#ifndef _CFGMGR32_H_
#define _CFGMGR32_H_

typedef DWORD CONFIGRET;

typedef DWORD DEVNODE, DEVINST;
typedef DEVNODE *PDEVNODE, *PDEVINST;
typedef CHAR *DEVNODEID_A, *DEVINSTID_A;
typedef WCHAR *DEVNODEID_W, *DEVINSTID_W;

#define CR_SUCCESS 0
#define CR_INVALID_DEVNODE  0x00000005
#define CR_INVALID_DEVINST  CR_INVALID_DEVNODE
#define CR_ACCESS_DENIED    0x00000033

#define MAX_GUID_STRING_LEN 39
#define MAX_CLASS_NAME_LEN  32
#define MAX_PROFILE_LEN     80

CONFIGRET WINAPI CM_Get_Device_ID_ListA( PCSTR, PCHAR, ULONG, ULONG );
CONFIGRET WINAPI CM_Get_Device_ID_ListW( PCWSTR, PWCHAR, ULONG, ULONG );
#define     CM_Get_Device_ID_List WINELIB_NAME_AW(CM_Get_Device_ID_List)

CONFIGRET WINAPI CM_Locate_DevNode_ExA( PDEVINST, DEVINSTID_A, ULONG, HANDLE );
CONFIGRET WINAPI CM_Locate_DevNode_ExW( PDEVINST, DEVINSTID_W, ULONG, HANDLE );

#endif /* _CFGMGR32_H_ */
